### PR TITLE
Attempt at adding negative truncation

### LINKED ISSUE #31: More powerful templates
I tried creating a custom template as follows:

```
notify:
  slack:
    webhook_url: ...
    channel: ...
    username: "New Release"
    on_success: true
    on_failure: true
    template: >
      Project: *<https://github.com/{{ repo.owner }}/{{ repo.name }}|{{ repo.name }}>* \n
      Version: *<https://github.com/{{ repo.owner }}/{{ repo.name }}/tree/{{ build.commit }}|{{ build.branch }}>* \n
      Author: *<https://github.com/{{ repo.owner }}/{{ repo.name }}/commit/{{ build.commit }}|{{ build.author }}>* \n
      Status: *<{{ sys.link }}|{{ build.status }}>*
```

There were a few problems:
1. `sys.link` was empty
2. It would have been nice if I could have extracted the tag from the `build.branch` similar to how [you extract the first 8 characters](https://github.com/drone-plugins/drone-slack/blob/release/0.4/main.go#L108) from `build.commit`

### PR DESCRIPTION
**Pull request by ProLoser**
I have never written go before in my life. Please be gentle.

Fixes #31

### CODE REVIEW

**Comment by Bugagazavr** [comment]
LGTM

**Comment by bradrydzewski** [comment]
some minor feedback ... I might look a bit messy with the casting, but might be a good idea to check absolute value to prevent an index out of bounds exception:

```
	if utf8.RuneCountInString(s) <= int(math.Abs(float64(len))) {
		return s
	}
```

the reason is that if you invoke the function with a negative value that exceeds the length of the string like this:

```
truncate("refs/heads/master", -21)
```

you can get a panic:

```
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
panic(0x102280, 0x1040a018)
	/usr/local/go/src/runtime/panic.go:500 +0x720
main.truncate(0x112f66, 0x11, 0x15, 0x1dbb, 0x0, 0x0)
	/tmp/sandbox604564321/main.go:20 +0x1a0
main.main()
	/tmp/sandbox604564321/main.go:9 +0x40
```

but otherwise the implementation looks good. I didn't know you could do `len = -len`, so you taught this Go programmer something with this PR :)

**Comment by ProLoser** [comment]
I actually didn't do that because it seemed overkill to import Math just for `abs()`

**Comment by tboerger** [comment]
Please create a PR on https://github.com/drone/drone-template-lib, after getting it into that we can trigger a new build to get it into this plugin.

**Pull request closed without merging**
