### PR TITLE
fix doc for drone 0.5 version.

### PR DESCRIPTION
**Pull request by appleboy**
recommend change `SLACK_WEBHOOK ` to `PLUGIN_WEBHOOK` for drone `0.5` version

Signed-off-by: Bo-Yi Wu <appleboy.tw@gmail.com>

### CODE REVIEW

**Comment by bradrydzewski** [comment]
the documentation is actually correct as-is.

`SLACK_WEBHOOK` is the name of the variable when using a secret. It is generally recommended to specify your slack webhook as a secret instead of in your .drone.yml where it can be compromised.

note that `PLUGIN_WEBHOOK` should never be set directly. If you are not using a secret the webhook should be specified directly in the `.drone.yml`:

```
   notify:
     slack:
       webhook: ...
```

Note that yaml variables are automatically converted by drone to environment variables. So in the above example the yaml `webhook` variable is converted to `PLUGIN_WEBHOOK`. The `PLUGIN_*` variables should never be directly set by an individual.

For more information on how secrets and variables work see the following document:
https://github.com/drone/drone-plugin-starter#drone-plugin-starter

**Comment by appleboy** [comment]
@bradrydzewski OK I got your point.

**Comment by tboerger** [comment]
In the latest merged pr this is already fixed, you can use a secret and also a yaml webhook key

**Comment by appleboy** [comment]
@tboerger Waiting for long time. Thanks.

**Pull request closed without merging**
