### PR TITLE
add DRONE_COMMIT_AUTHOR_EMAIL to available plugin

### PR DESCRIPTION
**Pull request by dlamotte**
Our company slack usernames match our email name before the @ sign.
This is just enough to get us to a point where we could mention the user
in slack when a pipeline fails.

### CODE REVIEW

**Comment by donny-dont** [comment]
@dlamotte if you want to reference users please check out https://github.com/drone-plugins/drone-slack-blame it uses the slack api to find a user based on the commit and can call them out privately or publicly dependent on what you want to do.

**Comment by dlamotte** [comment]
That looks like exactly what I need!  However, doesn't look to have the `SLACK_WEBHOOK` option.  Maybe the plugin is out of date?

Would this change still be accepted?  I definitely agree the other method would be better but... this might be good enough for some?

**Comment by donny-dont** [comment]
@dlamotte it uses the Slack API https://api.slack.com/custom-integrations/legacy-tokens and does not use a webhook.

**Comment by bradrydzewski** [comment]
I also recommend using the slack-blame plugin instead, since mapping the committer address to the  slack username is its primary feature.

**Comment by dlamotte** [comment]
Sure.  Will do.  We'll use this hacked one for a bit and I'll close this out.  I might send a PR to fix up the slack-blame plugin to bring it up to the new API.

Thanks all!

**Comment by donny-dont** [comment]
@dlamotte when I initially did the work legacy wasn't legacy. Looking here https://api.slack.com/docs/token-types there are a number of different token types. I think a bot one would technically work with everything.

If you have access to your slack to create a bot could you maybe give it a go with a bot token? I'm not sure how much updating things would actually need.

**Comment by dlamotte** [comment]
Sure, no worries.  I completely understand.  Didn't mean to offend and sorry if I did.

**Comment by donny-dont** [comment]
@dlamotte that wasn't it at all I'm actually really interested in you giving it a go. I made slack-blame because I felt that the webhook way of doing things didn't scale well. I found internally that people would just make a notification channel which then got ignored. So slack-blame was my response to make things more user friendly and get people actually looking at builds that break.

Also our slack since I implemented this got locked down quite a bit so its a bit of a bureaucracy to get a bot so I'd like to know the modern way of doing things 😄

**Comment by jesselang** [comment]
I can confirm that using a bot token does work for this plugin.

**Pull request closed without merging**
