### PR TITLE
Fixing docker plugin image

### PR DESCRIPTION
**Pull request by appleboy**
Also need update drone sig string.

cc @tboerger @bradrydzewski

### CODE REVIEW

**Comment by tboerger** [comment]
LGTM

**Comment by Bugagazavr** [comment]
LGTM

**Comment by Bugagazavr** [comment]
i keep it, because we need updated sig file

**Comment by appleboy** [comment]
@Bugagazavr Can you help to update sig file?

**Comment by Bugagazavr** [comment]
@appleboy you need @bradrydzewski to update sig file, or maybe @tboerger

**Comment by appleboy** [comment]
@Bugagazavr OK. Waiting feedback.

**Comment by bradrydzewski** [comment]
I can update the sig file in a few hours when I'm back at my computer

**Pull request merged**
