### PR TITLE
support environment variables related branch informations

### PR DESCRIPTION
**Pull request by takaishi**
Hello, I want to use variables that related branch for push or pull request. Drone support its by environment variables, so I add flags to drone-slack.

* [DRONE_REPO_BRANCH](https://docs.drone.io/pipeline/environment/reference/drone-repo-branch/)
* [DRONE_SOURCE_BRANCH](https://docs.drone.io/pipeline/environment/reference/drone-source-branch/)
* [DRONE_TARGET_BRANCH](https://docs.drone.io/pipeline/environment/reference/drone-target-branch/)

### CODE REVIEW

**Comment by tboerger** [comment]
This plugin should be simply migrated to our new plugin boilr template, than all vars should have a common naming and being available as variables.

**Comment by takaishi** [comment]
@tboerger 

OK, should we create 2 PR to use new boiler template and to support all variables, right?

**Comment by tboerger** [comment]
It should be one PR, the migration to the plugin lib would already include all the variables.

**Comment by donny-dont** [comment]
Fixed in #110

**Pull request closed without merging**
