### PR TITLE
add default commit.sha value in main.go

### PR DESCRIPTION
**Pull request by 9to6**
When I execute the command  ```drone exec --local```, a `panic` occurred in drone slack plugin.

https://github.com/drone-plugins/drone-slack/issues/28
I found this issue, but it's not applied yet. 
I think the panic is not good for users. 
So I send PR about this issue.

It added a line in the source code.

>add default value `unsetSHA`

After you apply this PR, when you execute ```drone exec``` you can see this message.
>*success* 9to6/test-drone#unsetSHA (master) by 9to6

Thanks for checking this comment.

### CODE REVIEW

**Comment by tboerger** [comment]
I would prefer a default like `00000000`, I think @bradrydzewski also did that within cncd.

**Comment by 9to6** [comment]
Thank you for replying.
What do you think of making PR again using default `00000000` you suggested?

**Comment by tboerger** [comment]
Just update this pr and it should be fine to merge :)

**Comment by tboerger** [comment]
@bradrydzewski when you are fine with this fix we can merge it. I have updated the pull request now.

**Pull request merged**
