### PR TITLE
Implement link_names support

### LINKED ISSUE #67: Add support for link-names=1
It should be nice to have an option to enable **link_names** when sending webhook request.  This will enable tagging people or channels.

https://api.slack.com/incoming-webhooks

It is simple parameter in json that is sent.

### PR DESCRIPTION
**Pull request by mdalp**
Fixes #67

As mentioned in the above GitHub issue added support for link_names.

It involves using my own version of the slack plugin https://github.com/drone-plugins/drone-slack/compare/master...mdalp:implement-link-names-support?expand=1#diff-70e973989f81df39acd35aa417b206bcR7 as this is not merged yet https://github.com/bluele/slack/issues/27 .

I am happy to wait for https://github.com/bluele/slack/issues/27  to be merged and update this PR.
If anyone needs this working now, here a working [docker image](https://hub.docker.com/r/mdalp/drone-slack/) with the feature implemented.

### CODE REVIEW

**Comment by tboerger** [comment]
So at least we will wait for the upstream lib

**Comment by mdalp** [comment]
Fair enough, sorted the upstream and in the meanwhile the dependency has been updated https://github.com/bluele/slack/pull/28 .

**Comment by tboerger** [comment]
So just updating the dependency is missing?

**Comment by mdalp** [comment]
No, that's been sorted when I sent my last comment, bluele merged my PR https://github.com/bluele/slack/pull/28 so now it should automatically be at the latest version. I am a newbie in golang but for my understanding the dependency should be updated automatically, am I correct?

**Comment by tboerger** [comment]
No, the dependency is not automatically updated, it's managed by govendor.

**Comment by tboerger** [comment]
Can you please file a PR for https://github.com/drone/drone-plugin-index/blob/master/content/drone-plugins/drone-slack/index.md to add this attribute?

**Pull request merged**
