### PR TITLE
Add `dry-run` flag

### PR DESCRIPTION
**Pull request by jesselang**
I would like to skip posting to slack based on run-time conditions. I didn't see a way to do that without adding a `dry-run` flag.

### CODE REVIEW

**Comment by bradrydzewski** [comment]
@jesselang can you provide more detail about the exact use case? You can use `when` clauses with any drone step, including a slack plugin step, to limit execution based on runtime conditions. 

The reason we have `--dry-run` for the docker plugin is that it helps people test and troubleshoot issues with docker-in-docker without publishing to a registry. I am not sure the same capability would be useful for this particular plugin.

**Comment by jesselang** [comment]
I've got repo A triggering a validation build of repo B with specific parameters:

```
pipeline:
  validate_b:
    image: custom/plugins/downstream
    params:
      - VALIDATION_BUILD=true
    repositories:
      - repo/b@master
```
I don't want a slack notification for these validation builds. I use the `when` clause to perform the step on `branch: master`. Is there a way to conditionalize a step based on an environment variable that isn't part of a matrix? I reviewed the docs, but didn't see an example that applied to environment variables. I would gladly have Drone handle this rather than add flags to each plugin. Let me know what our options are available. Thanks Brad.

**Comment by jesselang** [comment]
Hey @bradrydzewski. Is there a better way to achieve my goal of having steps be conditional based on an environment variable passed in as a build parameter? If so, I'd be happy to update the docs to make sure it gets externalized. Thanks!

**Comment by bradrydzewski** [comment]
I would use a deployment event with custom environment name (below). While the deployment event type might not seem like the right choice (based on name) it really isn't any different than a standard pipeline execution, and will let you filter steps based on named parameters.

```
pipeline:
  foo:
    image: bar
    when:
      environment: production
      event: deployment
```

**Pull request closed without merging**
